call plug#begin('~/.vim/plugged')
"Plug 'Raimondi/VimRegEx.vim'
"Plug 'kien/rainbow_parentheses.vim'
"Plug 'Decho'
Plug 'bling/vim-airline'
Plug 'chriskempson/base16-vim'
Plug 'flazz/vim-colorschemes'
Plug 'kien/ctrlp.vim'
Plug 'moll/vim-bbye'
Plug 'scrooloose/nerdtree', { 'on':  'NERDTree' }
Plug 'scrooloose/syntastic'
Plug 'ciaranm/securemodelines'
Plug 'tpope/vim-commentary'
"Plug '~/.vim/unplugged/VimFStar', { 'for': 'fstar', 'freeze': 1 }
call plug#end()

set nocompatible
set backspace=indent,eol,start

set background=dark
if has('gui_running')
   set guioptions-=T
   set guifont=Input\ Mono\ Condensed\\\,\ Medium\ Condensed\ 12
   " eliminate space at the bottom of the window when using with xmonad.
   set guiheadroom=0
   colorscheme manuscript
else
   let g:base16_shell_path='~/.vim/aux/base16-shell'
   colorscheme base16-twilight
endif

set ruler
set number
set wrap

set hidden

" tabs
set autoindent
set expandtab
set shiftwidth=3
set smartindent
set smarttab
set softtabstop=3
set tabstop=8

syntax enable
set hlsearch

let mapleader=","

" show trailing whitespace.
set list
" only show interesting whitespace.
if &listchars ==# 'eol:$'
   set listchars=tab:>\ ,trail:-,extends:>,precedes:<,nbsp:+
endif

" vim-airline
" -----------
let g:airline#extensions#tabline#enabled = 1
let g:airline_powerline_fonts = 1
" only show the basename, unless there's ambiguities.
let g:airline#extensions#tabline#formatter = 'unique_tail_improved'
"
" vim-bbye
" --------
noremap <Leader>q :Bdelete<CR>
"
" rainbow_parentheses
" -------------------
"au VimEnter * RainbowParenthesesToggle
"au Syntax * RainbowParenthesesLoadRound
"au Syntax * RainbowParenthesesLoadSquare
"au Syntax * RainbowParenthesesLoadBraces
"au Syntax * RainbowParenthesesLoadChevrons
"
" vim-ctrlp
" ---------
let g:ctrlp_user_command = [
    \ '.git', 'cd %s && git ls-files . -co --exclude-standard',
    \ 'find %s -type f'
    \ ]
"
" syntastic
" ---------
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
"let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
"let g:syntastic_debug = 1
"
" NERDtree
" --------
let NERDTreeQuitOnOpen=1

