call plug#begin('~/.vim/plugged')
Plug 'airblade/vim-gitgutter'
Plug 'bling/vim-airline'
Plug 'chriskempson/base16-vim'
Plug 'ciaranm/securemodelines'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'easymotion/vim-easymotion'
Plug 'flazz/vim-colorschemes'
Plug 'francoiscabrol/ranger.vim'
Plug 'huawenyu/neogdb.vim'
Plug 'majutsushi/tagbar'
Plug 'moll/vim-bbye'
Plug 'rust-lang/rust.vim'
Plug 'scrooloose/syntastic'
Plug 'tpope/vim-commentary'
Plug 'yggdroot/indentline'
call plug#end()

set nocompatible
set backspace=indent,eol,start
set ruler
set number
set wrap
set autoread
set hidden
set hlsearch

" default tab & indent settings
set shiftwidth=4
set softtabstop=4
set autoindent
set expandtab
set smartindent
set smarttab
set tabstop=8

" show trailing whitespace.
set list
" only show interesting whitespace.
if &listchars ==# 'eol:$'
   set listchars=tab:>\ ,trail:-,extends:>,precedes:<,nbsp:+
endif

if has('gui_running')
   set background=light
   set guioptions-=T
   set guifont=Input\ Mono\ Condensed\\\,\ Medium\ Condensed\ 13
   " eliminate space at the bottom of the window when using with xmonad.
   set guiheadroom=0
   colorscheme manuscript
else
   set background=dark
   let g:base16_shell_path='~/.vim/aux/base16-shell/scripts'
   colorscheme base16-tomorrow-night
endif

syntax enable

let mapleader=","

" vim-airline
let g:airline#extensions#tabline#enabled = 1
let g:airline_powerline_fonts = 1
" only show the basename, unless there's ambiguities.
let g:airline#extensions#tabline#formatter = 'unique_tail_improved'

" bbye
noremap <Leader>q :Bdelete<CR>
" alias bbye -> bclose
command! -bang -complete=buffer -nargs=? Bclose Bdelete<bang> <args>

" rainbow_parentheses
"au VimEnter * RainbowParenthesesToggle
"au Syntax * RainbowParenthesesLoadRound
"au Syntax * RainbowParenthesesLoadSquare
"au Syntax * RainbowParenthesesLoadBraces
"au Syntax * RainbowParenthesesLoadChevrons

" vim-ctrlp
let g:ctrlp_user_command = [
    \ '.git', 'cd %s && git ls-files . -co --exclude-standard',
    \ 'find %s -type f'
    \ ]

" syntastic
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
"let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
"let g:syntastic_debug = 1

" NERDtree
"let NERDTreeQuitOnOpen=1

" ranger.vim
let g:ranger_replace_netrw = 1

" tagbar
nmap <F8> :TagbarToggle<CR>

